### ISSUE TITLE
update license

### ISSUE THREAD

**Issue by jacobwilliams** [fortran-lang/minpack#13]
Just add the normal fortran-lang MIT style license on top of the other two existing ones? with: `Copyright (c) 2022 fortran-lang minpack contributors`?

**Comment by certik** [comment]
Yes, thanks!

**Comment by awvwgk** [comment]
I would think it is easier to maintain with a BSD-3-Clause license, since that one is closer in wording compared to the original Minpack license. Adding another license on top just makes the license expressions longer (`MIT AND BSD-3-Clause AND BSD-something`).

**Comment by milancurcic** [comment]
I don't think it's a problem as long as the project using minpack has a license compatible with all three. Do you know of a common permissive license that isn't?

**Comment by awvwgk** [comment]
That's true, still I don't see any advantage of adding another license on-top of the existing two. Either Jacob relicenses his changes to MIT or we continue this project in BSD-3-Clause, everything else doesn't make much sense IMO.
