### ISSUE TITLE
Setup a CI

### ISSUE THREAD

**Issue by certik** [fortran-lang/minpack#16]
Using GitHub actions, on Linux, macOS and Windows.

**Comment by jacobwilliams** [comment]
note: the existing one is still there, can be upgraded. 

Looks like it did run when you merged in #12. But it didn't run ahead of time? Is there some setting for that? I don't fully understand GitHub's logic for when it runs the CI if I'm not the owner of a project.

**Comment by awvwgk** [comment]
You set the CI up to run only on push:

https://github.com/fortran-lang/minpack/blob/0c758500cc5fee392cc37ad94526e522ad9136c4/.github/workflows/CI.yml#L2

You need to add the respective event to also run it for PRs.

**Comment by jacobwilliams** [comment]
Ah!!
