### ISSUE TITLE
Wrong intent for arguments to FCN() in example_lmder1.f90

### ISSUE THREAD

**Issue by certik** [fortran-lang/minpack#21]
Reported by @xecej4:

The INTENT of arguments fvec and fjac of subroutine FCN should be changed from OUT to IN OUT. As of now, when the subroutine is entered with iflag = 1, fjac becomes undefined; when entered with iflag = another value, fvec becomes undefined.

This subtle difference matters when flags such as NAG's -C=undefined or FTN95's /undef are used.

*Transferred from https://github.com/certik/minpack/issues/7*

**Comment by ivan-pi** [comment]
This also pops up on the Python side, see https://github.com/scipy/scipy/issues/9765
