### ISSUE TITLE
Modernize the examples

### ISSUE THREAD

**Issue by jacobwilliams** [fortran-lang/minpack#62]
Similar to what was done for the tests.

Should we move the examples into the test folder? Or is there a reason to keep them separate?

**Comment by epagone** [comment]
>Should we move the examples into the test folder? Or is there a reason to keep them separate?

fpm has separate concepts (and directories) for tests and examples. I personally think, as a perspective user, that this is the right way to go because they fulfil  different goals.

**Comment by ivan-pi** [comment]
I also think these are separate concepts. Examples should really be mini-apps, showing how MINPACK is used in practice. Examples should be commented heavily and have more of a "tutorial" purpose. In the future, examples could also be adapted to run in a dynamic environment such as Jupyter.
