### ISSUE TITLE
Minpack package manifest meta data

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/minpack#9]
The meta data in the package manifest seems somewhat inaccurate

https://github.com/fortran-lang/minpack/blob/2e94806b4490b4d2b49a87b6e78cd4e0d4c200e0/fpm.toml#L1-L5

For comparison the version by Ondřej @certik specifies

https://github.com/fortran-lang/minpack/blob/c0dc9cd5453bcdf8ba4fe79561a660b20e2332a9/fpm.toml#L1-L10

I think using a semantic version 1.0.0 would be more appropriate, however if the API was changed it should use 2.0.0 instead. Also, the author and copyright field seem incorrect in this version.

**Comment by jacobwilliams** [comment]
We can update it.

So far, no API changes... Except for the fact that they are in the module now, so a user of the old one would have to `use minpack`. So, maybe that is a breaking change, and we call it `2.0.0`?

**Comment by awvwgk** [comment]
> So far, no API changes... Except for the fact that they are in the module now, so a user of the old one would have to use minpack. So, maybe that is a breaking change, and we call it 2.0.0?

If you can't build existing code against the new minpack without changing something (even if it is just `use minpack`) it is API breakage (also consider that users from non-Fortran language probably have no way to access the old minpack API anymore as well). That would make 2.0.0 the correct version to choose.

**Comment by jacobwilliams** [comment]
Note: an iso-c-binding interface is definitely something we should make. Then those just call the module routines. 

Again this is another case of showing how modern Fortran should be done. So, not using FORTRAN77+f2py and calling it a day.
